### ISSUE TITLE
[Question] Contribution guidelines / questions

### ISSUE THREAD

**Issue by Hagith** [vituum/vituum#32]
Hello, first of all, big thanks for sharing Vituum :100: 
I'm migrating my SSG/MPA skeleton to Vite. And for that purpose Vituum & Handlebars plugin looks like a perfect fit!
During integration I found that setting `vite.root` causes some difficulties and I think I can propose some paths resolution improvements.
I have some questions related to development/contribution process:
- Which package manager you use during development? I couldn't find any "lock" file. Is there a particular reason for this?
- I would like to introduce some unit tests - can I setup up `vitest` for that? Or you have other preference?
- Have you considered setting up GitHub Action workflow for PR verification?
- Have you considered converting Vituum repository into monorepo?

**Comment by lubomirblazekcz** [comment]
Hi @Hagith,

what difficulties do you have with `vite.root`? And regarding your questions

- I am using npm, lock file is in gitignore, but should't be ooops
- I actually wanted to do some tests with `vitest`, but didn't really had the time and I focused on development without tests for now. So if you want to help with some tests, that would be great.
- Not really, since there are no tests and the project isn't that big and there were not a lot of contributions
- That's something I was thinking about in the beginning, but I've decided to go with separate repos and keep things simple

Thanks for the feedback though and yeah I am open to contributions. So if you do a PR and it's something that is in scope of this project and not really break changing then I will gladly merge it and do a new version 👍

**Comment by Hagith** [comment]
Thanks @lubomirblazekcz for quick response.

When I try to set `vite.root` to `./src`, to avoid prefixing everything inside templates eg. partials/scripts/styles. Then I cannot find a configuration which works both in serve and build. I will prepare a reproduction repo and PR with changes which should address that and we will get back to it there.

Monorepo is something I have not much experience, but I see most of the Vue/Vite ecosystems is using with pnpm and I think it fits here too. But this is deeper topic which I will get back eventually :)

I'm closing this issue as you answered my questions.
